### ISSUE TITLE
Request: Unbind A/D keys from moving head left/right when strafing.

### ISSUE THREAD

**Issue by chaosophy** [tr7zw/PaperDoll#11]
Hi, loving the mod but wondered one thing.
Would it be possible when in 'floaty' head mode to have an option where the head didn't move left/right when strafing with the a/d keys?
I notice that in third person view in game that it keeps the head still but actually rotates the body slightly left/right when strafing.  
So guessing your mod is picking up on that but due to the body being static the head moves instead?
No idea what's possible or what might look better, having some way of not having a/d move the head or mimicking the 3rd person view where it moves the body?

Thanks.

**Comment by tr7zw** [comment]
Check out the other head modes. The doll follows the 3d model, just that the torso is locked(not the head). That's why it looks like that.

**Comment by chaosophy** [comment]
Hi, thanks for the reply.  I've tried the other head modes and prefer the floaty mode.
No biggy, still liking the mod.  :)
