### ISSUE TITLE
Incompatible with Regeneration Mod

### ISSUE THREAD

**Issue by CatastropheChou** [tr7zw/PaperDoll#13]
https://pastebin.ubuntu.com/p/7B2vKy3pwk/

For Regeneration's end: https://github.com/Suff99/Regeneration/issues/397

**Comment by tr7zw** [comment]
The error seems to be something on Regenerations end, missing a null check in ``me.suff.mc.regen.util.ClientUtil.isAlex``.

**Comment by Suff99** [comment]
Cool mod guys
