### ISSUE TITLE
[BUG] Paperdoll+cosmetica crash

### ISSUE THREAD

**Issue by DanMeadWasTaken** [tr7zw/PaperDoll#16]
When joining a world/server, it simply crashes the whole client- seems to be a conflict between cosmetica cosmetics rendering and the paper doll rendering. for context i was using some of the cosmetics- so it could be how the cosmetics are being rendered including the fact that one of them hovers over the shoulder?

crash link given by notenoughcrashes (yes i know it's not recommended to use it, but the ability to not fully crash helps me to find the issue faster- so i only run it when i run into an issue)

https://bytebin.lucko.me/1C8w7Bq3LC

and the full log supplied by prism launcher 

https://mclo.gs/6GpSema

**Comment by tr7zw** [comment]
Somehow ``EntityRenderDispatcher.getSquaredDistanceToCamera`` crashes due to the camera being null, when cosmetica tries to get the distance... Honestly, no clue, since it also seems to try to render a nametag during the paperdoll rendering?!? Best-case open an issue on cosmeticas end instead.

**Comment by Volcan4436** [comment]
Hmm interesting don't know why that broke tbh my Cheat Client I develop has a paper doll and it's fine and it shows the Cosmetica cosmetics and Nametag can you send your mod your using

**Comment by Volcan4436** [comment]
I just checked the mod I will take a look at my source code to see if it is the same and if so I can probably fix the mod for you

**Comment by DanMeadWasTaken** [comment]
As the issue seems to either have fixed itself or been fixed, i'll be closing this- basically, one way or another, it stopped crashing
