### ISSUE TITLE
(1.19.4) Model don't render properly when using elytras

### ISSUE THREAD

**Issue by GRUI72** [tr7zw/PaperDoll#17]
Quilt 0.18.5
QFAPI 6.0.0 beta-2+0.76.0
Video below.
1.19.3:

https://user-images.githubusercontent.com/91282421/226625337-6be0a2ba-dae7-448d-ad32-f034d48b7e46.mp4

1.19.4:

https://user-images.githubusercontent.com/91282421/226625426-ddd10bf4-40e5-4db6-ab1a-bd08523065c4.mp4

Configs are same.
Nothing written in the logs.

**Comment by tr7zw** [comment]
It runs in 1.19.4? Honestly assumed that it wouldn't even boot, that's why the files are not marked to work with 1.19.4.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/226728503-772becd4-5234-44e7-b906-fec070eaa7ae.png)
I guess fun fact: the same issue has been present in the vanilla inventory since elytra's have been added.

**Comment by tr7zw** [comment]
After wasting 1+ hour on this, still no clue where the hell this rotation comes from. I'm freezing literally all values, still, the body rotates. Going to do something more productive.

**Comment by tr7zw** [comment]
This took over 2 hours of my life, just because Mojang moved that value to a really random place... 🥲
