### ISSUE TITLE
Port to 1.20.4

### ISSUE THREAD

**Issue by dima-dencep** [tr7zw/PaperDoll#26]
The version for 1.20.2 works on 1.20.4, but crashes when opening the config

**Comment by tr7zw** [comment]
Rn working on Firstperson update 1.20.4(-1.16.5? maybe later). Not sure when I'll get to this mod.

**Comment by tr7zw** [comment]
You can download a dev build with 1.20.4 Fabric/Forge/NeoForge(new) from the actions tab above. Consider giving feedback if everything works.
