### ISSUE TITLE
Transparent skin does not render correctly

### ISSUE THREAD

**Issue by Oururis** [tr7zw/PaperDoll#31]
1.20.4
Skins containing transparent parts do not render correctly
For example, this skin ![RainbowGlass](https://github.com/tr7zw/PaperDoll/assets/118568742/a010c711-918c-44a6-a47d-00cd65622094)

**Comment by tr7zw** [comment]
Not much I can do about that. I think sodium will have a translucent sort soon, which might help fix transparency issues.
