### ISSUE TITLE
The Doll is Mirrored on the X-Axis for some reason no matter the setting

### ISSUE THREAD

**Issue by TheCrafter8000** [tr7zw/PaperDoll#33]

**Comment by tr7zw** [comment]
Any more info like mc version? I had to rewrite quiet a bit of the logic cause in 1.20.6 otherwise the entity is rotated the wrong way around, same with the lighting. Possible I accidentally mirrored the view matrix while doing that, but I need to know which mc version.

**Comment by TheCrafter8000** [comment]
My MC version is 1.20.6 and the mod version is 1.2.1 for fabric

**Comment by JDWMGB** [comment]
> My MC version is 1.20.6 and the mod version is 1.2.1 for fabric

Also happens on MC 1.21 with version 1.22 for fabric
