### ISSUE TITLE
[1.2.2] The paper doll appears to be rendered at a low FPS In Minecraft version 1.21.

### ISSUE THREAD

**Issue by qarty1** [tr7zw/PaperDoll#36]
This is a list of the mods I applied below :

> continuity-3.0.0-beta.5+1.21
> fabric-api-0.100.4+1.21
> indium-1.0.33+mc1.21
> iris-1.7.3+mc1.21
> modmenu-11.0.1
> sodium-fabric-0.5.9+mc1.21
> Xaeros_Minimap_24.2.1_Fabric_1.21
> XaerosWorldMap_1.38.8_Fabric_1.21
> paperdoll-fabric-1.2.2-mc1.21

The animation of the paper doll appears to be around 30FPS, and there was no problem when running it with a previous version of the launcher.

**Comment by tr7zw** [comment]
It would be 20FPS, as thats what mc updates at. Fun fact: the player in the inventory also just updates in 20fps. I'll have to take a look, possible that due to 1.21 changes the workaround for that broke.

**Comment by qarty1** [comment]
Here is a comparison video

https://github.com/user-attachments/assets/0d1aa0ae-31d6-4a54-b9ed-22e2db00a856
(1.21)

https://github.com/user-attachments/assets/1e1a3344-7e7c-4d93-8397-2efef8964424
(1.20.2)
