### ISSUE TITLE
capes appear when used with physical mods

### ISSUE THREAD

**Issue by QAQlinmiao** [tr7zw/PaperDoll#40]
When the pro version of the physics mod and paper doll are installed, the bottom of the screen can always be covered with a cape
![2024-09-17_23 09 06](https://github.com/user-attachments/assets/2f1fd70f-1c88-4395-8ec5-920bfff03124)
When the paper doll is hidden
The capes will also disappear
![2024-09-17_23 09 59](https://github.com/user-attachments/assets/7d6c6823-e43f-4256-9595-9e4fd95d2545)
mod version:
paperdoll-forge-1.2.3-mc1.20.1
physics-mod-pro-v171b-forge-1.20.1

**Comment by tr7zw** [comment]
That's more likely a bug with physics mod in combination with the shader and paper doll.

**Comment by QAQlinmiao** [comment]
Can it be fixed?
I also escalated the problem to the other party

**Comment by tr7zw** [comment]
Not aware of anything I could do. My best guess is that physics mod needs to fix it.

**Comment by QAQlinmiao** [comment]
Okay, I'm going to report the problem to the other party

**Comment by tr7zw** [comment]
Closing, as it's a Physicsmod issue.
