### ISSUE TITLE
Disable render in F1

### ISSUE THREAD

**Issue by JakeTeeEm** [tr7zw/PaperDoll#43]
Perhaps an option to disable rendering when F1 is enabled?
Annoyingly is present for screenshots

**Comment by tr7zw** [comment]
F6.

**Comment by JakeTeeEm** [comment]
Where does the mod say that?  Is there somewhere in the controls or somewhere to change it because it's not working for me.
I'm on v1.2.3, 1.21.1, Fabric Loader version 0.16.7

**Comment by tr7zw** [comment]
Wait wrong mod. paper doll should turn off during f1 as it's rendered as part of the ui that gets turned off. I'll check
