### ISSUE TITLE
[Suggestion] More Flexible Offset Position (Slider)

### ISSUE THREAD

**Issue by ardissaps** [tr7zw/PaperDoll#5]
Maybe the slider can go further? A little more far from edge of screen, thanks nice mods very useful

**Comment by tr7zw** [comment]
Yea I can look into allowing higher values in the sliders. Note that you can use the config file to set "invalid" too large values, but it requires restarting the game.

**Comment by ardissaps** [comment]
I see, I would put the paper doll beside the minimap on the left bottom so it would look like Dota 2 interface,  dream come true.

**Comment by tr7zw** [comment]
In the 1.19 release I've doubled the slider min/max values, so it should be no issue now.

**Comment by tr7zw** [comment]
Noteworthy: these values are not validated, so you can edit them in 1.19/in the config file, and it will work for 1.18 etc.

**Comment by ardissaps** [comment]
Thank you! (there actually a mod that can whuuz any slider to be further that it supposed to be (coz I stil on 1.18.2), but I yet not tested, hopefully they will work).

**Comment by tr7zw** [comment]
Yea the "Slider" mod(or how it's called) will work too, probably simplest way is to get the right values in 1.19 and then use that config for 1.18. I also backmerged that change to the 1.18 version, but I'll not make a new release just for that, so you could also download the latest 1.18 build from the github actions(the file without anything  like -all/-javadoc/-src).
