### ISSUE TITLE
[Crash / 1.19.2 / Forge] When I using goat horn the game crashes.

### ISSUE THREAD

**Issue by murao-kun** [tr7zw/PaperDoll#9]
[crash-2022-08-20_00.36.03-client.txt](https://github.com/tr7zw/PaperDoll/files/9385521/crash-2022-08-20_00.36.03-client.txt)

**Comment by tr7zw** [comment]
That's some other mod with a weird check, not this mod/vanilla.

**Comment by murao-kun** [comment]
Eww, hot can I find what is causing that?

**Comment by murao-kun** [comment]
Turned out this was a forge bug. Fixed in the version after 1.19.2 RB.
